### ISSUE TITLE
Virtualbox VM clock runs 25% slow

### ISSUE THREAD

**Issue by chetstone** [docker/toolbox#193] opened 2015-09-18 04:28 UTC
After installing Docker Toolbox and running my container, I noticed the clock was way off. I read through [boot2docker issue 290](https://github.com/boot2docker/boot2docker/issues/290) but that mainly concerns problems when the host goes to sleep, and is supposed to have been fixed by [PR 661](https://github.com/boot2docker/boot2docker/pull/661). My problem has nothing to do with the host sleeping, the clock runs slow all the time. It is so slow that the ntpd daemon added by PR 661 does not work at all. When I run `sudo ntpclient -s -h \${NTP_SERVER}` the time gets set but not exactly -- it is still several seconds behind at best. I decided to put that command into cron to run every minute. When it runs it sets the clock within a couple of seconds but within that minute, until the next cron run it looses 10 to 20 seconds !!! This is causing me some problems because my docker process communicates with a database running on the host and the time skew is causing trouble. 

Does the Virtualbox installed by docker toolbox include the Guest Additions? I may be naive but I don't understand why NTP should be required at all... I would think it would be the responsibility of Virtualbox to keep its VM's in sync with the host.

More information on my installation is [here](http://wp.me/p1P6Hm-1K).

**Comment by mchiang0610** [comment] 2015-09-18 09:52
@chetstone Thanks for sharing this. Do you have problems using providers other than Virtualbox? 

cc'ing Machine / b2d maintainers: @ehazlett @nathanleclaire @tianon

**Comment by ehazlett** [comment] 2015-09-18 13:24
@chetstone yes we include the guest additions however virtualbox still seems to sometimes have timing issues so we include ntp.  What is your host OS and what version of VirtualBox are you using?

**Comment by chetstone** [comment] 2015-09-18 14:21
Haven't tried docker with other providers. Although I've been running a similar setup under Parallels 10/Ubuntu and had no such issues. My host is MacOSX Yosemite 10.10.4. Virtualbox is 5.0.4. 

Interestingly, the problem went away just one hour after starting the every-minute sync. 
Here's a log showing the guest (2nd column) almost a minute behind the host (1st column), then syncing up and falling behind a couple of times, then, at 4:51:18 syncing up exactly and staying that way. For 10 hours so far. Don't know what'll happen if I reboot host or guest.

```
(22:49:31)[crystal: ~]$ while /usr/bin/true; do printf "%s  %s\n" "`date -u`" "`docker-machine ssh default date`"; sleep 1; done
Fri Sep 18 04:49:41 UTC 2015  Fri Sep 18 04:48:52 UTC 2015
Fri Sep 18 04:49:42 UTC 2015  Fri Sep 18 04:48:52 UTC 2015
Fri Sep 18 04:49:43 UTC 2015  Fri Sep 18 04:48:53 UTC 2015
Fri Sep 18 04:49:45 UTC 2015  Fri Sep 18 04:48:54 UTC 2015
Fri Sep 18 04:49:46 UTC 2015  Fri Sep 18 04:48:55 UTC 2015
Fri Sep 18 04:49:47 UTC 2015  Fri Sep 18 04:48:56 UTC 2015
Fri Sep 18 04:49:49 UTC 2015  Fri Sep 18 04:48:57 UTC 2015
Fri Sep 18 04:49:50 UTC 2015  Fri Sep 18 04:48:58 UTC 2015
Fri Sep 18 04:49:51 UTC 2015  Fri Sep 18 04:48:59 UTC 2015
Fri Sep 18 04:49:53 UTC 2015  Fri Sep 18 04:49:00 UTC 2015
Fri Sep 18 04:49:54 UTC 2015  Fri Sep 18 04:49:54 UTC 2015
Fri Sep 18 04:49:55 UTC 2015  Fri Sep 18 04:49:55 UTC 2015
Fri Sep 18 04:49:56 UTC 2015  Fri Sep 18 04:49:56 UTC 2015
Fri Sep 18 04:49:58 UTC 2015  Fri Sep 18 04:49:56 UTC 2015
Fri Sep 18 04:49:59 UTC 2015  Fri Sep 18 04:49:57 UTC 2015
Fri Sep 18 04:50:00 UTC 2015  Fri Sep 18 04:49:58 UTC 2015
Fri Sep 18 04:50:01 UTC 2015  Fri Sep 18 04:49:58 UTC 2015
Fri Sep 18 04:50:03 UTC 2015  Fri Sep 18 04:49:59 UTC 2015
Fri Sep 18 04:50:04 UTC 2015  Fri Sep 18 04:49:59 UTC 2015
Fri Sep 18 04:50:05 UTC 2015  Fri Sep 18 04:50:00 UTC 2015
Fri Sep 18 04:50:07 UTC 2015  Fri Sep 18 04:50:01 UTC 2015
Fri Sep 18 04:50:08 UTC 2015  Fri Sep 18 04:50:02 UTC 2015
Fri Sep 18 04:50:09 UTC 2015  Fri Sep 18 04:50:03 UTC 2015
Fri Sep 18 04:50:10 UTC 2015  Fri Sep 18 04:50:04 UTC 2015
Fri Sep 18 04:50:12 UTC 2015  Fri Sep 18 04:50:04 UTC 2015
Fri Sep 18 04:50:13 UTC 2015  Fri Sep 18 04:50:05 UTC 2015
Fri Sep 18 04:50:14 UTC 2015  Fri Sep 18 04:50:06 UTC 2015
Fri Sep 18 04:50:15 UTC 2015  Fri Sep 18 04:50:07 UTC 2015
Fri Sep 18 04:50:17 UTC 2015  Fri Sep 18 04:50:07 UTC 2015
Fri Sep 18 04:50:18 UTC 2015  Fri Sep 18 04:50:08 UTC 2015
Fri Sep 18 04:50:19 UTC 2015  Fri Sep 18 04:50:08 UTC 2015
Fri Sep 18 04:50:20 UTC 2015  Fri Sep 18 04:50:09 UTC 2015
Fri Sep 18 04:50:22 UTC 2015  Fri Sep 18 04:50:10 UTC 2015
Fri Sep 18 04:50:23 UTC 2015  Fri Sep 18 04:50:11 UTC 2015
Fri Sep 18 04:50:24 UTC 2015  Fri Sep 18 04:50:12 UTC 2015
Fri Sep 18 04:50:26 UTC 2015  Fri Sep 18 04:50:13 UTC 2015
Fri Sep 18 04:50:27 UTC 2015  Fri Sep 18 04:50:13 UTC 2015
Fri Sep 18 04:50:28 UTC 2015  Fri Sep 18 04:50:14 UTC 2015
Fri Sep 18 04:50:29 UTC 2015  Fri Sep 18 04:50:15 UTC 2015
Fri Sep 18 04:50:31 UTC 2015  Fri Sep 18 04:50:16 UTC 2015
Fri Sep 18 04:50:32 UTC 2015  Fri Sep 18 04:50:18 UTC 2015
Fri Sep 18 04:50:33 UTC 2015  Fri Sep 18 04:50:19 UTC 2015
Fri Sep 18 04:50:35 UTC 2015  Fri Sep 18 04:50:20 UTC 2015
Fri Sep 18 04:50:36 UTC 2015  Fri Sep 18 04:50:21 UTC 2015
Fri Sep 18 04:50:37 UTC 2015  Fri Sep 18 04:50:22 UTC 2015
Fri Sep 18 04:50:39 UTC 2015  Fri Sep 18 04:50:23 UTC 2015
Fri Sep 18 04:50:40 UTC 2015  Fri Sep 18 04:50:23 UTC 2015
Fri Sep 18 04:50:41 UTC 2015  Fri Sep 18 04:50:24 UTC 2015
Fri Sep 18 04:50:42 UTC 2015  Fri Sep 18 04:50:25 UTC 2015
Fri Sep 18 04:50:44 UTC 2015  Fri Sep 18 04:50:26 UTC 2015
Fri Sep 18 04:50:45 UTC 2015  Fri Sep 18 04:50:27 UTC 2015
Fri Sep 18 04:50:46 UTC 2015  Fri Sep 18 04:50:28 UTC 2015
Fri Sep 18 04:50:47 UTC 2015  Fri Sep 18 04:50:29 UTC 2015
Fri Sep 18 04:50:49 UTC 2015  Fri Sep 18 04:50:30 UTC 2015
Fri Sep 18 04:50:50 UTC 2015  Fri Sep 18 04:50:31 UTC 2015
Fri Sep 18 04:50:51 UTC 2015  Fri Sep 18 04:50:33 UTC 2015
Fri Sep 18 04:50:53 UTC 2015  Fri Sep 18 04:50:34 UTC 2015
Fri Sep 18 04:50:54 UTC 2015  Fri Sep 18 04:50:36 UTC 2015
Fri Sep 18 04:50:56 UTC 2015  Fri Sep 18 04:50:37 UTC 2015
Fri Sep 18 04:50:57 UTC 2015  Fri Sep 18 04:50:39 UTC 2015
Fri Sep 18 04:50:59 UTC 2015  Fri Sep 18 04:50:40 UTC 2015
Fri Sep 18 04:51:00 UTC 2015  Fri Sep 18 04:50:42 UTC 2015
Fri Sep 18 04:51:02 UTC 2015  Fri Sep 18 04:50:43 UTC 2015
Fri Sep 18 04:51:03 UTC 2015  Fri Sep 18 04:50:44 UTC 2015
Fri Sep 18 04:51:04 UTC 2015  Fri Sep 18 04:50:46 UTC 2015
Fri Sep 18 04:51:05 UTC 2015  Fri Sep 18 04:50:47 UTC 2015
Fri Sep 18 04:51:07 UTC 2015  Fri Sep 18 04:50:48 UTC 2015
Fri Sep 18 04:51:08 UTC 2015  Fri Sep 18 04:50:49 UTC 2015
Fri Sep 18 04:51:09 UTC 2015  Fri Sep 18 04:50:51 UTC 2015
Fri Sep 18 04:51:11 UTC 2015  Fri Sep 18 04:50:52 UTC 2015
Fri Sep 18 04:51:12 UTC 2015  Fri Sep 18 04:50:53 UTC 2015
Fri Sep 18 04:51:13 UTC 2015  Fri Sep 18 04:50:55 UTC 2015
Fri Sep 18 04:51:15 UTC 2015  Fri Sep 18 04:50:56 UTC 2015
Fri Sep 18 04:51:16 UTC 2015  Fri Sep 18 04:50:58 UTC 2015
Fri Sep 18 04:51:18 UTC 2015  Fri Sep 18 04:51:19 UTC 2015
Fri Sep 18 04:51:20 UTC 2015  Fri Sep 18 04:51:20 UTC 2015
Fri Sep 18 04:51:21 UTC 2015  Fri Sep 18 04:51:21 UTC 2015
Fri Sep 18 04:51:23 UTC 2015  Fri Sep 18 04:51:23 UTC 2015
Fri Sep 18 04:51:24 UTC 2015  Fri Sep 18 04:51:24 UTC 2015
Fri Sep 18 04:51:25 UTC 2015  Fri Sep 18 04:51:25 UTC 2015
Fri Sep 18 04:51:26 UTC 2015  Fri Sep 18 04:51:27 UTC 2015
Fri Sep 18 04:51:28 UTC 2015  Fri Sep 18 04:51:28 UTC 2015
Fri Sep 18 04:51:29 UTC 2015  Fri Sep 18 04:51:29 UTC 2015
Fri Sep 18 04:51:30 UTC 2015  Fri Sep 18 04:51:31 UTC 2015
Fri Sep 18 04:51:32 UTC 2015  Fri Sep 18 04:51:32 UTC 2015
Fri Sep 18 04:51:33 UTC 2015  Fri Sep 18 04:51:33 UTC 2015
Fri Sep 18 04:51:34 UTC 2015  Fri Sep 18 04:51:35 UTC 2015
Fri Sep 18 04:51:36 UTC 2015  Fri Sep 18 04:51:36 UTC 2015
Fri Sep 18 04:51:37 UTC 2015  Fri Sep 18 04:51:37 UTC 2015
Fri Sep 18 04:51:38 UTC 2015  Fri Sep 18 04:51:39 UTC 2015
Fri Sep 18 04:51:40 UTC 2015  Fri Sep 18 04:51:40 UTC 2015
Fri Sep 18 04:51:41 UTC 2015  Fri Sep 18 04:51:42 UTC 2015
Fri Sep 18 04:51:43 UTC 2015  Fri Sep 18 04:51:43 UTC 2015
Fri Sep 18 04:51:44 UTC 2015  Fri Sep 18 04:51:44 UTC 2015
Fri Sep 18 04:51:45 UTC 2015  Fri Sep 18 04:51:46 UTC 2015
Fri Sep 18 04:51:47 UTC 2015  Fri Sep 18 04:51:47 UTC 2015
Fri Sep 18 04:51:48 UTC 2015  Fri Sep 18 04:51:48 UTC 2015
Fri Sep 18 04:51:49 UTC 2015  Fri Sep 18 04:51:50 UTC 2015
Fri Sep 18 04:51:51 UTC 2015  Fri Sep 18 04:51:51 UTC 2015
Fri Sep 18 04:51:52 UTC 2015  Fri Sep 18 04:51:52 UTC 2015
Fri Sep 18 04:51:53 UTC 2015  Fri Sep 18 04:51:54 UTC 2015
Fri Sep 18 04:51:55 UTC 2015  Fri Sep 18 04:51:55 UTC 2015
Fri Sep 18 04:51:56 UTC 2015  Fri Sep 18 04:51:57 UTC 2015
Fri Sep 18 04:51:58 UTC 2015  Fri Sep 18 04:51:58 UTC 2015
Fri Sep 18 04:51:59 UTC 2015  Fri Sep 18 04:51:59 UTC 2015
Fri Sep 18 04:52:00 UTC 2015  Fri Sep 18 04:52:01 UTC 2015
Fri Sep 18 04:52:02 UTC 2015  Fri Sep 18 04:52:03 UTC 2015
Fri Sep 18 04:52:04 UTC 2015  Fri Sep 18 04:52:04 UTC 2015
Fri Sep 18 04:52:05 UTC 2015  Fri Sep 18 04:52:05 UTC 2015
Fri Sep 18 04:52:06 UTC 2015  Fri Sep 18 04:52:06 UTC 2015
Fri Sep 18 04:52:08 UTC 2015  Fri Sep 18 04:52:08 UTC 2015
Fri Sep 18 04:52:09 UTC 2015  Fri Sep 18 04:52:09 UTC 2015
Fri Sep 18 04:52:10 UTC 2015  Fri Sep 18 04:52:11 UTC 2015
```

**Comment by chetstone** [comment] 2015-09-19 03:59
Well, that was an anomaly. As soon as I stopped running `date` every second on the VM, the clock started going crazy again. And I cannot get the "sane" behaviour to repeat again, either by running `ntpclient` every minute or `date` every second or both.

 I also removed my container and the bare VM is still behaving the same way. I've rebooted the host a couple of times too.

**Comment by chetstone** [comment] 2015-09-20 15:14
I have found a workaround for this. First, I trashed Virtualbox and installed 5.0.4 again from the Oracle site. That did not help --- the issue was still present. But replacing it with 4.3.30 fixed the issue.

**Comment by mchiang0610** [comment] 2015-09-21 16:38
@chetstone Thanks for letting us know your fix.

**Comment by aaronbbrown** [comment] 2015-10-20 21:02
I also have this issue, setting the following VirtualBox properties helped, but the clock still jumps all over the place:

```sh
VBoxManage guestproperty set $DOCKER_MACHINE_NAME "/VirtualBox/GuestAdd/VBoxService/--timesync-set-on-restore" 1
VBoxManage guestproperty set $DOCKER_MACHINE_NAME "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold" 1000
VBoxManage guestproperty set $DOCKER_MACHINE_NAME "/VirtualBox/GuestAdd/VBoxService/--timesync-interval" 10000
VBoxManage guestproperty set $DOCKER_MACHINE_NAME "/VirtualBox/GuestAdd/VBoxService/--timesync-min-adjust" 100
```

**Comment by mchiang0610** [comment] 2015-10-21 22:31
Closing this because it's not a bug from Toolbox.

**Comment by nathanleclaire** [comment] 2015-10-21 22:59
Hold on there cowboy.  As the saying goes, "It may not be your fault, but it is your problem".  Without any sort of workaround or resolution, I'd at least like to leave the issue open to continue getting information from users.

**Comment by mchiang0610** [comment] 2015-10-21 23:06
@nathanleclaire Thanks, we will keep this open. However, this is outside of toolbox's control.

**Comment by nathanleclaire** [comment] 2015-10-21 23:12
I think it might make a better fit as a boot2docker/boot2docker issue.  Maybe we can move it there?

**Comment by jeffdm** [comment] 2016-02-18 00:00
@nathanleclaire agreed!

@chetstone sorry for the delay - best to ask in `boot2docker/boot2docker` as it seems specific to the VM. Thanks for creating an issue!

**Closed by jeffdm** 2016-02-18 00:00 UTC
Labels: bug, mac

**Comment by lox** [comment] 2016-03-16 03:47
@jeffdm what happened to "It may not be your fault, but it is your problem"? Is there another issue that has been created elsewhere that replaces this one?

**Comment by nathanleclaire** [comment] 2016-03-16 17:45
@lox Seems @chetstone hadn't followed up on the boot2docker/boot2docker repo (or at least didn't link to this one).  Please open an issue at https://github.com/boot2docker/boot2docker/issues/new if you're experiencing issues with this.  IIRC, Tianon added in some new ntp sync code to b2d a while back that should help to alleviate this class of issues somewhat, but we need to know if people are still having problems.  Thanks!

**Comment by onilira** [comment] 2017-08-17 18:17
I just came here to say that i was having the same problem running Docker on Windows. Virtualbox version was 5.1 so i followed @chetstone advice and downgraded to 4.3.30 and it just worked.
