### ISSUE TITLE
connection forcibly closed

### ISSUE THREAD

**Issue by niccokunzmann** [docker/toolbox#340] opened 2015-12-10 22:45 UTC
I am Having an issue with Windows 7 Professional SP1 64 bit:

    >docker-machine create --driver virtualbox my-default
    Error loading driver "virtualbox": dial-http tcp 127.0.0.1:1867: read tcp 127.0.0.1:1868->127.0.0.1:1867: wsarecv: An existing connection was forcibly closed by the remote host.

Kinematic also fails. Toolbox version: 1.9.1c.

**Comment by nathanleclaire** [comment] 2015-12-12 02:03
Do you have VPN / firewall in your environment?

**Comment by niccokunzmann** [comment] 2015-12-12 07:50
I have no VPN. There is the Windows Firewall. I deactivated Avast.

**Comment by kenheal** [comment] 2015-12-14 15:41
I see the same, I am using a Windows 2012R2 virtual machine with vhv.enable = TRUE set in the .vmx file, and am also using v1.9.1c, though I get the same result with earlier versions.
A click on Docker Quickstart Terminal yields:
Creating Machine default...
Creating CA: C:\Users\Administrator\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\Administrator\.docker\machine\certs\cert.pem
Running pre-create checks...
Error creating machine: Error with pre-create check: write tcp 127.0.0.1:52634->127.0.0.1:52633: wsasend: An existing connection was forcibly closed by the remote host.
Looks like something went wrong... Press any key to continue...

**Comment by kenheal** [comment] 2015-12-14 17:45
Administrator@Win2012docker MINGW64 /c/Program Files/Docker Toolbox
$ ./docker-machine.exe version
C:\Program Files\Docker Toolbox\docker-machine.exe version 0.5.2 ( 0456b9f )

Administrator@Win2012docker MINGW64 /c/Program Files/Docker Toolbox
$ ./docker-machine.exe create -d virtualbox default
Running pre-create checks...
Creating machine...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
WARNING >>> Error attempting heartbeat call to plugin server: read tcp 127.0.0.1:49308->127.0.0.1:49307: wsarecv: sting connection was forcibly closed by the remote host.
Error creating machine: Error in driver during machine creation: read tcp 127.0.0.1:49308->127.0.0.1:49307: wsarec existing connection was forcibly closed by the remote host.

**Comment by kenheal** [comment] 2015-12-14 17:52
$ ./docker-machine.exe -D create -d virtualbox default
Docker Machine Version: 0.5.2 ( 0456b9f )
Found binary path at .\docker-machine-driver-virtualbox.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:49338
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling .Close
Successfully made call to close driver server
Found binary path at .\docker-machine-driver-virtualbox.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:49342
() Calling .GetVersion
Using API Version 1
() Calling .SetConfigRaw
() Calling .GetMachineName
(default) Calling .GetMachineName
(default) Calling .DriverName
(default) Calling .GetCreateFlags
(default) Calling .SetConfigFromFlags
Running pre-create checks...
(default) Calling .PreCreateCheck
(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | 5.0.10r104061
(default) DBG | }
(default) DBG | STDERR:
(default) DBG | {
(default) DBG | }
(default) DBG | COMMAND: wmic cpu get VirtualizationFirmwareEnabled
(default) DBG | STDOUT:
(default) DBG | {
(default) DBG | VirtualizationFirmwareEnabled
(default) DBG | TRUE
(default) DBG |
(default) DBG | }
(default) Calling .GetConfigRaw
Creating machine...
(default) Calling .Create
(default) Creating VirtualBox VM...
(default) DBG | Creating disk image...
(default) Creating SSH key...
(default) DBG | Creating 20000 MB hard disk image...
Error creating machine: Error in driver during machine creation: read tcp 127.0.0.1:49343->127.0.0.1:49342: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by nathanleclaire** [comment] 2015-12-14 21:20
@niccokunzmann The log files we need are mostly the result of running `docker-machine` with `--debug` flag.

@kenheal VPN / firewall in your environment?  It's clear that something is blocking the connection to `127.0.0.1`.

**Comment by kenheal** [comment] 2015-12-14 21:37
@nathanleclaire Thx for the reply.

No VPN in this environment, the standard Windows firewall is running; which programs/services would need to be added to the allow list?  Tried disabling firewall completely but got same result.  No antivirus either on the test machine.

**Comment by nathanleclaire** [comment] 2015-12-14 21:41
@kenheal Hm.  No proxy either then?  Any funny business with networking in general to report (custom hosts file settings, etc.)?

Can you successfully launch a server on a `localhost` / `127.0.0.1` port and connect to it using different software?  (e.g. a small Go program etc.)

**Comment by kenheal** [comment] 2015-12-14 23:19
The system is a standalone server (no domain). Even disabling the firewall makes no difference, though I never entirely trust Microsoft Windows firewall not to get in the way,
What program/service provides the server side of the connection and/or what firewall rules should I create for it?

**Comment by nathanleclaire** [comment] 2015-12-15 00:32
> What program/service provides the server side of the connection and/or what firewall rules should I create for it?

Pre-0.5.3: `docker-machine-driver-virtualbox.exe`
0.5.3: `docker-machine.exe`

**Comment by kenheal** [comment] 2015-12-17 13:30
Even completely disabling the firewall makes no difference, I still see the same error.

**Comment by nathanleclaire** [comment] 2015-12-18 17:37
@kenheal I am interested in getting you to try some binaries with additional debugging info soon on this problem if you are willing. Stay tuned.

**Comment by kenheal** [comment] 2015-12-18 17:40
@nathanleclaire Would be more than happy to do so.  Thanks.

**Comment by nathanleclaire** [comment] 2015-12-18 22:59
@kenheal @niccokunzmann Please try this binary: http://sf.glassbeadga.me/bin/docker-machine_windows-amd64.exe (some changes and additional logging -- SHA256 sum for this binary is `6b63676c7c29b491be19758e4f23815a0199ec0fc33901dee411818abb090b4f`) and paste the output to gist.github.com when you get a chance.  Thanks!  Will be invaluable to help track down the source of this bug.

**Comment by niccokunzmann** [comment] 2015-12-20 13:58
I do not know if this helps. @kirstin created a [description of how to install the toolbox under windows](https://github.com/niccokunzmann/cp-docker-development/blob/master/docker/windows/InstallDockerUnderWindows.md#installing-docker-under-windows) so I can use it.

**Comment by kenheal** [comment] 2015-12-22 09:21
@nathanleclaire Attempted to download binary, but connection seems to timeout.
C:\Temp>wget http://sf.glassbeadga.me/bin/docker-machine_windows-amd64.exe
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2015-12-22 10:20:58--  http://sf.glassbeadga.me/bin/docker-machine_windows-amd64.exe
Resolving sf.glassbeadga.me... 192.241.207.154
Connecting to sf.glassbeadga.me|192.241.207.154|:80... failed: Connection timed out.

**Comment by kenheal** [comment] 2015-12-22 09:58
Thx for the tip @niccokunzmann -- will try this after trying @nathanleclaire 's debug binary.

**Comment by kenheal** [comment] 2015-12-22 12:48
I tried @niccokunzmann 's tip but unfortunately the result remained the same.
(https://gist.github.com/kenheal/44aa79f244ca393b0be2)

**Comment by kpalf** [comment] 2015-12-22 16:17
@nathanleclaire - I'm also happy to try a debug binary if you can make one available.  Sounds similar to #2318

**Comment by nathanleclaire** [comment] 2015-12-28 18:41
Hi @kenheal @kpalf I forgot I was hosting that binary there (and have nuked the server) but I'll see if I can throw another one up for you.

**Comment by jeffdm** [comment] 2016-02-26 00:38
Thanks for the issue @niccokunzmann and for the input @kenheal @nathanleclaire @kpalf . Merging this with https://github.com/docker/toolbox/issues/153.

**Closed by jeffdm** 2016-02-26 00:38 UTC

**Comment by parzibyte** [comment] 2020-03-26 04:11
I had this problem and it was caused by openvpn (just if someone in the future comes here). First try to close it from the taskbar, and if it does not work, Go to Task Manager > Details > Search openvpnserver and stop it
