### ISSUE TITLE
Migrate from existing boot2docker-vm Failed

### ISSUE THREAD

**Issue by tonytan4ever** [docker/toolbox#271] opened 2015-11-04 23:18 UTC
When I am trying to migrate boot2docker to docker-machine, I encountered this:

``` 
$ docker-machine -D create -d virtualbox --virtualbox-import-boot2docker-vm boot2docker-vm docker-vm
Docker Machine Version: 0.5.0 (04cfa58)
Found binary path at /usr/local/bin/docker-machine-driver-virtualbox
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:51899
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(flag-lookup) Calling RpcServerDriver.GetCreateFlags
Making call to close connection to plugin binary
Making call to close driver server
(flag-lookup) Calling RpcServerDriver.Close
Successfully made call to close driver server
Found binary path at /usr/local/bin/docker-machine-driver-virtualbox
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:51903
() Calling RpcServerDriver.GetVersion
Using API Version 1
() Calling RpcServerDriver.SetConfigRaw
() Calling RpcServerDriver.GetMachineName
(docker-vm) Calling RpcServerDriver.GetMachineName
(docker-vm) Calling RpcServerDriver.DriverName
(docker-vm) Calling RpcServerDriver.GetCreateFlags
(docker-vm) Calling RpcServerDriver.SetConfigFromFlags
Running pre-create checks...
(docker-vm) Calling RpcServerDriver.PreCreateCheck
(docker-vm) DBG | COMMAND: /usr/local/bin/VBoxManage
(docker-vm) Calling RpcServerDriver.GetConfigRaw
(docker-vm) Calling RpcServerDriver.GetConfigRaw
Creating machine...
(docker-vm) Calling RpcServerDriver.Create
(docker-vm) DBG | COMMAND: /usr/local/bin/VBoxManage controlvm boot2docker-vm poweroff
(docker-vm) OUT | Creating VirtualBox VM...
(docker-vm) DBG | STDOUT:
(docker-vm) DBG | {
(docker-vm) DBG | }
(docker-vm) DBG | STDERR:
(docker-vm) DBG | {
(docker-vm) DBG | VBoxManage: error: Machine 'boot2docker-vm' is not currently running
(docker-vm) DBG | }
(docker-vm) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo docker-vm --machinereadable
(docker-vm) DBG | STDOUT:
(docker-vm) DBG | {
(docker-vm) DBG | }
(docker-vm) DBG | STDERR:
(docker-vm) DBG | {
(docker-vm) DBG | VBoxManage: error: Could not find a registered machine named 'docker-vm'
(docker-vm) DBG | VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
(docker-vm) DBG | VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2719 of file VBoxManageInfo.cpp
(docker-vm) DBG | }
Error creating machine: Error in driver during machine creation: /usr/local/bin/VBoxManage showvminfo docker-vm --machinereadable failed:
VBoxManage: error: Could not find a registered machine named 'docker-vm'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2719 of file VBoxManageInfo.cpp
```

**Comment by jeffdm** [comment] 2015-11-06 00:54
Thanks for the issue

cc @nathanleclaire

**Comment by nathanleclaire** [comment] 2015-11-06 21:32
It was broken by machine 94361315a812e06d80edd20a3a19e4ac3d5b392f cc @dgageot

Essentially, the `getInfo` call runs on the current driver VM (which does not exist yet), not the boot2docker VM as intended in the original code.  My bad, I should have caught it in review.

**Comment by dmp42** [comment] 2015-11-06 22:23
@dgageot first regression \o/

![fiestafrogs](https://cloud.githubusercontent.com/assets/332946/11010208/f3b6b0a2-8491-11e5-869c-248b1e91cc9c.jpg)

**Comment by nathanleclaire** [comment] 2015-11-06 22:50
I'm working on a patch to fix it.

**Comment by nathanleclaire** [comment] 2015-11-07 01:14
https://github.com/docker/machine/pull/2212

**Comment by SvenDowideit** [comment] 2016-02-07 04:05
@jeffdm can we close this?

**Comment by tonytan4ever** [comment] 2016-02-08 14:42
As I have tested last in 0.5.6, it has been fixed.

**Closed** 2016-02-08 16:17 UTC
Labels: bug, docker-machine
