### ISSUE TITLE
Hangs a "Setting environment variables for machine default..."

### ISSUE THREAD

**Issue by keski** [docker/toolbox#249] opened 2015-10-20 06:12 UTC
Docker Quickstart Terminal frequently hangs on ```Setting environment variables for machine default...``` on Windows 10. Closing and re-running sometimes resolves it, but not always.

**Comment by mchiang0610** [comment] 2015-10-20 06:22
@keski Hey, thanks for reporting.  cc/ @nathanleclaire

**Comment by aadrian** [comment] 2015-10-25 10:36
The same for windows 8.1.

Can't really use it :(.

**Comment by codex73** [comment] 2015-11-02 18:37
I've found a work around solution that **works for me** when "Quickstart  Terminal" hangs on start with message "Setting environment variables for machine default...". This problem is replicated every time I hibernate or sleep the computer.

I'm running "Windows 8.1", Virtual Box 5.0.6 and latest Toolbox.

**Steps I Take** 

*check virtual box default vm is "Powered Off", if not, right click on VM, "Close", "Power Off"
*within virtual box, go to File -> Preferences -> Network -> Host-only Networks and remove all adapters.

Now when I open "Quickstart  Terminal" it doesn't hang and it also creates the necessary adapter again, this time with no conflict.

:memo: Note: the above might not work for you, shared these details with all in case they do.

**Comment by mikewchicago13** [comment] 2015-11-11 14:29
I ran "docker-machine rm default" to remove it. Then, I ran the Docker Quickstart again, which created machine named default from scratch.
This resolved the issue on my computer.

**Comment by codex73** [comment] 2015-11-11 14:43
Cool. I could be wrong here but I think when the default docker vm is removed all of the containers within are as well. That's good solution regardless. For me, I have too many containers already working so I opted for alternate solution.

**Comment by keski** [comment] 2015-12-10 13:10
This issue was resolved for me in the last release (1.9.1c) on  Windows 7/10. I also tested it successfully on Windows 8.1 but not extensively.

**Comment by jeffdm** [comment] 2016-02-19 00:30
@keski - good to hear.

In any case, I believe the root cause would be with the `env` command in [`docker/machine`](http://github.com/docker/machine). Bringing the conversation there might yield more focused help!

Going to close this for now but please feel free to re-open

**Closed by jeffdm** 2016-02-19 00:30 UTC
Labels: bug, docker-machine
