### ISSUE TITLE
Exit status 255

### ISSUE THREAD

**Issue by kevinSuttle** [docker/toolbox#66] opened 2015-08-12 19:37 UTC
This is what happens after running the Docker QuickStart Terminal.app for me.

<img width="805" alt="screen shot 2015-08-12 at 3 33 55 pm" src="https://cloud.githubusercontent.com/assets/95672/9234640/f6d694a0-4107-11e5-8ab0-750e6ecb5835.png">

**Comment by jeffdm** [comment] 2015-08-12 19:37
Thanks! Are there any logs if you scroll up?

**Comment by kevinSuttle** [comment] 2015-08-12 19:38
Ah, there are. Didn't see those. 
```bash
Starting VM...
Too many retries.  Last error: Maximum number of retries (60) exceeded
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...

```

**Comment by jeffdm** [comment] 2015-08-12 22:05
Thanks! Looking.

**Comment by kranthides** [comment] 2015-08-13 03:45
I am facing the similar issue after updating from boot2docker to docker tools in Mac

**Comment by vijayrawatsan** [comment] 2015-08-13 04:01
Facing the same issue

**Comment by hoang0** [comment] 2015-08-13 14:51
I'm having a similar issue running Docker in Windows 8.1: 

![image](https://cloud.githubusercontent.com/assets/9540909/9252930/bc4ce6f6-41a0-11e5-88e8-b4a981244146.png)

The docker-machine env command instruction is not clear. Let me know what you guys find out.

**Comment by ameyrk** [comment] 2015-08-14 13:02
Same issue

**Comment by ameyrk** [comment] 2015-08-16 12:56
Looks like this happens when you leave system idle for a long time on windows 8.1. I am checking this and let you know if I find more information.

**Comment by ameyrk** [comment] 2015-08-16 16:50
Hi All,

The below issue is replicable on Windows 8.1. However, I am not sure on other OS. 

![issue](https://cloud.githubusercontent.com/assets/13772520/9294000/ebbd147c-4436-11e5-9b0d-d83df0cfbe1f.png)

This happens, when you leave the system idle and eventually systems falls asleep. When you login back this issue happens.  The command "docker-machine.exe env default" hangs and gives no o/p. You get the same error if you close the client and re-open it and also, no matter how many times you restart the virtual machine, the issue will persist. The only solution to get rid of this problem is you have to restart your machine.

Looks like I have found the problem, please see the below screenshot and the steps.

1. I started my windows machine and launched the "Docker Quick Start Terminal" it launches as usual without any errors. 
2. Now I went to the windows cmd terminal and played the "ipconfig  /all" command. My left hand side window (please see the below screen shot) is the screen grab of the command "ipconfig  /all" in windows cmd terminal. 
3. Now I leave my machine idle and make it fall asleep. 
4. I wake my machine from sleep and re-login.
5. Now I play the "docker-machine.exe env default" command in the docker client terminal it hangs and produces no o/p.
6. I close the docker client terminal and relaunch it. The issue persists (1st screenshot)
7. Now this time, I run the "ipconfig  /all"  in windows cmd terminal. My right hand side window (please see the below screen shot) is the screen grab of the command "ipconfig  /all" in windows cmd terminal.  Here you see , new attributes "Autoconfiguration IPV4 address & subnet mask" are added under the section "Ethernet adapter VirtualBox Host-Only Network #2:" . And also IPV4 address is marked as duplicate. 

![duplicate-ip](https://cloud.githubusercontent.com/assets/13772520/9294169/06715f0c-443d-11e5-87d3-ad75cf092f97.PNG)

Could you please look into this issue?

Thanks,
Amey

**Comment by wjimenez5271** [comment] 2015-08-17 22:50
Having similar issue:
```
 $  docker-machine start default
exit status 1
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
``` 

then when I run that:

```
$ docker-machine env
Error: Expected either one machine name, or -u flag to unset the variables in the arguments.
```

or 

```
$ docker-machine env default
default is not running. Please start this with docker-machine start default
```

**Comment by wjimenez5271** [comment] 2015-08-17 22:59
upon further investigation it might be a different root cause, created a ticket to track it here: https://github.com/docker/toolbox/issues/105

**Comment by ryguyrg** [comment] 2015-08-24 04:39
Also was seeing this issue.  Stopped + removed 'default' VM from VirtualBox and re-ran this command:
 . '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'

This worked.

**Comment by michaeljs1990** [comment] 2015-08-26 06:32
@ryguyrg just tried this and it's not working for me.

**Comment by michaeljs1990** [comment] 2015-08-26 06:41
upgrading to the test build of virtual box worked for me and seems to also have worked for many others. Shame the install process on mac is still a pain. boot2docker was not fun to use as well.

**Comment by princesspanda** [comment] 2015-08-27 21:40
Doing what @ryguyrg did worked for me.

**Comment by yurishkuro** [comment] 2015-09-02 20:12
Following  @ryguyrg suggestion:
```
Creating Machine default...
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...
```
and it hangs here. If I re-run the command in another terminal:
```
Machine default already exists in VirtualBox.
Starting machine default...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
Setting environment variables for machine default...
[ docker image ]
Password:
```
and it hangs on password prompt. This is with a fresh install of the toolbox, downloaded on Sep-02.

**Comment by kevinSuttle** [comment] 2015-09-02 20:45
@jeffdm Any ideas?

**Comment by Diego81** [comment] 2015-09-03 15:40
I am facing the same issue

**Comment by jason13** [comment] 2015-09-03 18:10
Try "docker-machine ls" see if the default machine status is Timeout, then stop it. 
Try "docker-machine ls" see if the status become Stop. And close terminal windows. 
Relaunch Docker Quick Start Terminal again and it work again. 
It work for me.

**Comment by yurishkuro** [comment] 2015-09-03 19:14
@jason13 just tried that, the machine was indeed in Timeout status. After I stopped it and ran Quick Start, the quick start script in one terminal locked up after this output

```
$ . '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
Machine default already exists in VirtualBox.
Starting machine default...
Starting VM...
```

Is this supposed to hang?

When I ran the same quick start from another terminal, it looks like it worked, I got back to the prompt, and the `docker` command is working.

**Comment by jason13** [comment] 2015-09-03 19:16
It won't hang but run a little longer then before. I think it might back to normal when you run next time.

**Comment by yurishkuro** [comment] 2015-09-03 19:21
huh, so I Ctrl-C killed that process, and it also fell back into prompt. Maybe there's a bug there that makes it wait forever for something.

**Comment by towry** [comment] 2015-09-06 12:55
> Looks like this happens when you leave system idle for a long time on windows 8.1. I am checking this and let you know if I find more information.

I have the same issue, it seems that I have to restart my mac to solve the problem.

**Comment by tiangolo** [comment] 2015-09-09 02:18
@ameyrk nailed it down for Windows in this comment https://github.com/docker/toolbox/issues/66#issuecomment-131580971. 

I confirm the same issue happens in Windows 7:

After a sleep / wake cycle, Windows detects the Host-Only network as a "duplicate" and changes its IP. After that, docker-machine (or the Quickstart terminal) doesn't work anymore.

It is probably caused by this VirtualBox bug (from 4 years ago): https://www.virtualbox.org/ticket/9151, so there doesn't seem to be a fix soon from VirtualBox. And it's probably a Windows bug.

-----------

**The quick workaround that worked for me was:**

* Open VirtualBox
* Go to File -> Preferences -> Network -> Host-only Networks
* Docker Toolbox probably created a second Host-only network, probably named "VirtualBox Host-Only Ethernet Adapter # 2", double click that
* Change the "IPv4 Address" from something like 192.168.99.1 to something like 192.168.99.2 (you will probably have to increase / decrease the IP every time). But it's important that the IP actually changes.
* Hit OK. If the IP changed (it should have changed), you will be prompted for you "Windows Administrator OK" (or however it's named).

After that, the docker-machine and the Quickstart Terminal should work, and that way, you don't have to restart your whole Windows.

**Comment by ameyrk** [comment] 2015-09-09 05:47
@tiangolo thanks for the update. I will try to use your work around for windows 8.1.


Best Regards,
Amey

**Comment by eproxus** [comment] 2015-09-09 08:43
@tiangolo That doesn't explain it happening on OS X though, does it?

**Comment by tiangolo** [comment] 2015-09-09 11:41
I hope it works @ameyrk.

No @eproxus, it's probably a different problem (I don't have a Mac to test).
But nevertheless, this issue is one of the first hits in Google for that other problem in Windows and has several comments related, so I posted the workaround here first. 
Actually, there's another issue for the Windows bug ( #116 ) but that doesn't have many comments and doesn't show up in Google so easily, so it would be harder for people searching in Google to find the solution only there.

**Comment by towry** [comment] 2015-09-10 02:26
I notice that this issue may related to the computer's ip address, in my work place the ip is 10.240.x.x, and in my home the ip is 192.168.99.x, and the ip of virtual box is 192.168.99.x, so docker works fine at the work place but not at the home. and at the home, if i do not connect to the internet, the docker works fine.

**Comment by eproxus** [comment] 2015-09-10 08:13
@tiangolo @towry @jeffdm 

So, to summarize, there seems to be three separate issues:

1. The Windows issue, where wake from sleep breaks Docker
2. The OS X issue (of which #66 was my original report) where the VM and host network have  different IP ranges, but Docker Machine still can't connect to the VM
3. The IP issue, where the VM and host network have overlapping IP ranges which seems to be solved by changing either range

I'd prefer those being tracked in separate issues, right now the discussion here is quite messy.

**Comment by eproxus** [comment] 2015-09-10 10:18
It seems nr 2 above is solved in the latest version of `docker-machine` (see #118).

**Comment by towry** [comment] 2015-09-10 13:01
@eproxus I solved my problem by changing my router's gateway IP address from 192.168.99.1 to 10.106.23.1, the ip of Virtualbox is still 192.168.99.1

**Comment by markjbrown** [comment] 2015-09-29 13:46
Is this issue still open? I installed Docker QuickStart on a Windows 8.1 machine yeserday and have not been able to get it to work. I have uninstalled and reinstalled it to no avail. I have tried ALL of the reported fixes above but am still looking at a long running "Starting VM..." line followed by a max retries error.

I am also trying to run this docker-machine env command from bash but I'm getting all sorts of errors that tells me that just running that command is not what I am supposed to do so how do I run this command?


Machine default already exists in VirtualBox.
Starting machine default...
Starting VM...
Too many retries.  Last error: Maximum number of retries (60) exceeded
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.

**Comment by Spanizen** [comment] 2015-09-30 06:50
I tried to run the lastest 1.8.2c version in windows. All set of installations are proper but when i check the docker client verison

$ docker verision

The Client OS is displayed as Linux when we checked it in windows OS
![docker client os defect](https://cloud.githubusercontent.com/assets/9822417/10186269/2968c11e-676d-11e5-9c1a-24f9e2ea714f.png)

Please suggest

Thanks

**Comment by populov** [comment] 2015-10-01 06:41
Looks like on my system for some reason DHCP for virtual network adapter became disabled and it causes error.
You can fix it by setting DHCP settings back manually. Or, like @tiangolo suggested above, change it's IP address and Docker Toolbox will create a new one with appropriate settings.

![vbox1](https://cloud.githubusercontent.com/assets/3766033/10214357/d0a8add6-6830-11e5-9868-e5eac745e100.png)
![vbox2](https://cloud.githubusercontent.com/assets/3766033/10214356/d0a6a18a-6830-11e5-9ce7-4d5fba96ce36.png)

**Comment by alphabytes** [comment] 2015-10-01 11:59
Hello All,

i changed the DHCP IP for adapter #2 and still i am facing the same issue.

In docker toolbox:
"You will want to check the provider to make sure the machine and associated resources were properly removed.
Looks like something went wrong... Press any key to continue..."


and i tried running the vm directly from virtualbox i got this...

Failed to open a session for the virtual machine default.
Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter' (VERR_INTNET_FLT_IF_NOT_FOUND).
Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND).
Result Code: E_FAIL (0x80004005)
Component: ConsoleWrap
Interface: IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

my virtualbox version is latest 5.0.4r102546
i tried all the above suggestions, nothing worked.

**Comment by gdm85** [comment] 2015-10-08 07:30
Also affected here with docker-machine on Mac OS X (not yet El Capitan)

**Comment by michaeljs1990** [comment] 2015-10-10 08:54
100% Fresh install of El Capitan with no modifications made yet. Installed Docker Toolbox and get this error when starting up the VM.

**Comment by gdm85** [comment] 2015-10-10 11:51
I built docker-machine from master and that worked, so I think something was fixed there

**Comment by michaeljs1990** [comment] 2015-10-10 18:20
So very odd issue... I was fighting with this and trying to recreate it in various way tweaking setting but i finally just tried to ssh into the machine using

```
ssh docker@localhost -p 52350
```

You can find the port for your machine in the virtualbox settings as it might be different.

When i ran this it game me the output of

```
Bad owner or permissions on /Users/michael/.ssh/config
```

I went in and chmod 755'ed that file as well as setting my id_rsa to 600 which is had not been before. After doing this i removed and recreated the machine and everything worked... I wonder how many of these issues are being caused by odd ssh config files or bad permissions.

**Comment by mcMickJuice** [comment] 2015-10-16 23:58
@michaeljs1990 I'm trying what you posted and i don't even see a config file in this directory. Only a github_rsa file...  I'm assuming that's part of my problem

**Comment by meeleem** [comment] 2015-10-20 07:15
I had the issue with error message "Get http://127.0.0.1:2375/v1.20/version: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it..
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?" (routed from another issue to discussion here). 

What solved the issue for me (on Win 8.1) was: 
- I deleted the default installed container
- Run CMD as admin
- Re-run the start.sh from directory "..\Docker Toolbox"

Not sure whether this helps anyone but at least this solved the error regarding "no connection".

**Comment by NataliaMetelskaya** [comment] 2015-10-21 18:39
@meeleem thank you! it helps, just resolved the same issue on Win 7.

**Comment by michaeljs1990** [comment] 2015-10-21 18:43
anyone who gets this issue please print out the output of

```
ssh docker@localhost -p {{ ssh port }}
```

you can find ssh port in `docker-machine inspect default`. Every issue seems to be related to this although you are fixing it in different ways i'm almost positive at this point the underlying issue is the VM coming up with an invalid authorized_keys file.

**Comment by mchiang0610** [comment] 2015-10-21 22:57
Possible to continue this dialog inside #153 ? Trying to merge all the issues to really help us troubleshoot further.

**Closed by mchiang0610** 2015-10-21 22:57 UTC
Labels: bug, docker-machine

**Comment by michaeljs1990** [comment] 2015-10-21 23:02
It does not look to be the same issue to me. Although the very last post in here belongs in the ticket you mentioned this issue is much more likely to show up when googling for the 255 error which seems to be an ssh issue.

**Comment by mchiang0610** [comment] 2015-10-21 23:04
@michaeljs1990 It's not always the same issue, but we are trying to get down to the bottom of this with the Docker machine team as well. A centralized place for machine issue will help with that. 

This isn't an error with Toolbox. 

from machine team: 255 is a generic error code

**Comment by michaeljs1990** [comment] 2015-10-21 23:06
Got you didn't read the ticket title well enough. Should the other ticket redirect to the machine repo? The only reason I have been posting in here is because this has much more info on the issue then the actual machine repository.

**Comment by mchiang0610** [comment] 2015-10-21 23:14
@michaeljs1990 Thanks. Sorry for the misunderstanding. I am just doing what helps the machine team the most. 

We have seen a lot of exit status 255 issues from Kitematic and Toolbox, and they are not always caused by the same issue it seems. Having a place for the machine team to just go in and help in my opinion is beneficial. We can certainly re-open this issue if you feel reopening will be more helpful.

**Comment by DanHenry4** [comment] 2015-11-05 21:58
@meeleem Thanks.

I was getting the "connection actively refused" message. Deleting the machine from VirtualBox and running ./start.sh in a BASH got it to work.

**Comment by CChapin-G** [comment] 2015-11-13 01:04
@meeleem ++, Thanks, your workaround solved the "connection actively refused" for me as well.  My procedure matches what @DanHenry4 also did.

**Comment by haneefkassam** [comment] 2015-12-01 06:59
@meeleem Thanks!!  Your fix worked!  I just deleted the vm, then ran the quickstart termnial as admin and it worked fine.  Must've been something in setting up the ssh keys (connection was actively refused by the destination) or something that required admin privileges.

**Comment by vinaydate** [comment] 2015-12-06 13:28
@meeleem Worked, Thanks

**Comment by CowPanda** [comment] 2016-02-01 06:48
@yurishkuro Thanks!

I'm run this script in iTerm2 and it worked for me. 

    $ . '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
   Machine default already exists in VirtualBox.
   Starting machine default...
   Starting VM...

**Comment by galioy** [comment] 2016-02-08 12:17
For me the process hung on 

```
Machine default already exists in VirtualBox.
Starting machine default...
Starting VM...
```

and I interrupted the process forcefully and that caused the problem with `error code 255`. Tried to remove the VMs, but in the end a simple restart of my Mac did fix the issue.

**Comment by toamitkumar** [comment] 2016-05-12 03:08
The process was hung for me as well. Found I was on an older version of VB, upgrading fixed it

**Comment by HananBahy** [comment] 2019-03-02 09:10
problem :Exit status 255
solution:
1-I turn off  'default' machine from VM virtualBox .
2-then open Quick start terminal and it works .
