### ISSUE TITLE
Symlinks Issue with DockerToolbox-1.8.2a VM

### ISSUE THREAD

**Issue by radamsfc** [docker/toolbox#200] opened 2015-09-23 17:38 UTC
I just installed DockerToolbox-1.8.2a and previously working 'npm install' now fails with the symlink issues

  npm ERR! Linux 4.0.7-boot2docker
  npm ERR! argv "npm" "install"
  npm ERR! node v0.12.2
  npm ERR! npm  v2.7.4
  npm ERR! path ../mime/cli.js
  npm ERR! code EPROTO
  npm ERR! errno -71

  npm ERR! EPROTO, symlink '../mime/cli.js'
  npm ERR!

It appears it is an issue known in VirtualBox.  It appears this version of ToolBox installed 5.0.4.

There is a known issue with 5.0.4 described also here

https://github.com/npm/npm/issues/9624

And tracked here

https://www.virtualbox.org/ticket/14563

**Comment by vallettea** [comment] 2015-09-24 07:53
same issue here.
the problem is that the virtualbox 5.0.5 is not yet available for mac so we're stuck until then.
Do you think we should downgrade ?

**Comment by mchiang0610** [comment] 2015-09-24 10:18
@radamsfc @vallettea Thanks for this. Yes, please downgrade for now. Once an update for VirtualBox arrives, we will update the toolbox.

**Comment by neurosnap** [comment] 2015-09-26 00:31
I'm having the same issue on Windows 8.1, the 5.0.5 build linked in the npm issue is for OS X only, I guess I'll downgrade virtualbox for now, does anyone know of a working version to install?

**Comment by zettvs** [comment] 2015-10-17 09:24
upgrading from 5.0.4 to to 5.0.6 solved that issue for me (OS X)

**Comment by rdsubhas** [comment] 2015-10-20 12:12
Just another thing to watch out for: Make sure Virtualbox Extension Pack is installed (some people miss this and it produces the same symlink error outlined above)

**Comment by mchiang0610** [comment] 2015-10-21 22:54
Thanks! 

Closing this issue for now because we are shipping with the latest virtualbox.

**Closed by mchiang0610** 2015-10-21 22:54 UTC
Labels: bug

**Comment by cinic** [comment] 2016-07-14 11:24
On Windows 10 not working.
