### ISSUE TITLE
Error creating machine: Error in driver during machine creation: Maximum number of retries (5) exceeded

### ISSUE THREAD

**Issue by benmarwick** [docker/toolbox#273] opened 2015-11-05 14:45 UTC
I'm on Windows 7, VirtualBox 5.0.4, Docker toolbox 1.9.0. When I run the quickstart I get:

```
Creating Machine default...
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: Maximum number of retries (5) exceeded
Looks like something went wrong... Press any key to continue...
```

But I do get a running 'default' VM when I open VirtualBox and have a look. In my VBox.log I see (full file is [here](http://pastebin.com/wJwJ9NDP)): 

```
00:00:00.696246 HM: HMR3Init: VT-x w/ nested paging and unrestricted guest execution hw support
```

So maybe VT-X support is ok for me. Right at the end of the logfile I see somthing ominous about D-Bus not being installed:

    00:00:46.950561 VMMDev: Guest Log: 00:00:10.018836 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed

The D-Bus issue has been reported here https://github.com/docker/toolbox/issues/214 When I run the quickstart again directly after this, I get an error message about getting an IP address:

```
Machine default already exists in VirtualBox.
Setting environment variables for machine default...
Error running connection boilerplate: Error getting driver URL: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :


                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/

Error getting IP address: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  :
docker is configured to use the default machine with IP
For help getting started, check out the docs at https://docs.docker.com
NOTE: When using interactive commands, prepend winpty. Examples: 'winpty docker run -it ...', 'winpty docker exec -it ...'.
```

And if I run a command, I get another message relating to connecting:

```
$ winpty docker run hello-world
An error occurred trying to connect: Post http://localhost:2375/v1.21/containers
/create: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made bec
ause the target machine actively refused it.
```

At this point I went to https://www.virtualbox.org/wiki/Testbuilds and got VirtualBox 5.0.9, and then uninstalled Docker Toolboox, deleted the default VM and the .docker directory, and reinstalled the Toolbox, and re-run it, and got the same problem:

```
Creating Machine default...
Creating CA: C:\Users\marwick\.docker\machine\certs\ca.pem
Creating client certificate: C:\Users\marwick\.docker\machine\certs\cert.pem
Running pre-create checks...
Creating machine...
Error creating machine: Error in driver during machine creation: Maximum number of retries (5) exceeded
Looks like something went wrong... Press any key to continue...

```

The logfile for this attempt is here: http://pastebin.com/9VjD9t6P

How can I get this working?

**Comment by elan100cs** [comment] 2015-11-16 09:29
I have the same exact error, i tried to lower the virtualbox version to 4.3, but still has the same error.

**Comment by philltomlinson** [comment] 2015-11-16 16:06
+1

**Comment by elan100cs** [comment] 2015-11-17 02:41
Okay i found a solution for this, upgrading to the latest virtualbox 5.0.10 seems to fixed the problem.

**Comment by adyromantika** [comment] 2015-11-17 07:50
I had the problem earlier but it turned out that dhcp is off on the VirtualBox host only network that the docker "default" image attaches to. I'm on OSX but I think Windows too needs the "default" virtual machine to handle all the containers.

**Comment by unguiculus** [comment] 2015-11-18 08:35
Upgrading to Virtualbox 5.0.10 temporarily fixed the problem yesterday. Today the problem is back again.

**Comment by seregasheypak** [comment] 2015-11-18 15:33
+1 
`docker-machine create --driver virtualbox default` - works

`docker ps` **Cannot connect to the Docker daemon. Is the docker daemon running on this host?**

 `docker-machine env default` **doesn't work also**
```
Error running connection boilerplate: Error getting driver URL: Something went wrong running an SSH command!
command : ip addr show dev eth1
err     : exit status 255
output  : 
```

**Comment by josiahsprague** [comment] 2015-11-18 18:10
I had the same issue. VirtualBox 5.0.8 r103449. To fix it, I checked the Network info on the `default` image, and found out which host only network it was attaching to (`vboxnet21` in this case);
<img width="756" alt="screen shot 2015-11-18 at 1 07 27 pm" src="https://cloud.githubusercontent.com/assets/516388/11249536/6b7bd6c8-8df5-11e5-8059-f231d5aa41a7.png">

Then I went to Virtual Box > Preferences > Network > Host-only Networks > `vboxnet21` > Edit > DHCP Server, where I added the IP addresses in @adyromantika's screenshot above. Restarted the Docker Quickstart Terminal, and everything appears to be working.

**Comment by seregasheypak** [comment] 2015-11-18 19:44
Thanks, it helped. Is it a bug?

**Comment by amok** [comment] 2015-11-24 03:09
+1
solution provided by @josiahsprague didn't help me

**Comment by kcraft** [comment] 2015-11-24 04:21
I have the same problem. Performing the above steps does not work for me (my DHCP setup already matched the screenshot above). I am running on VirtualBox 5.0.10 on Mac OS/X Yosemite 10.10.5.

**Comment by csu** [comment] 2015-11-28 05:21
Same problem here. Tried reconfiguring the DHCP setup and it didn't work. Here's what I'm getting:

    csu:~$ bash --login '/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
    Machine default already exists in VirtualBox.
    Starting machine default...
    exit status 1
    Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): Regenerating TLS certificates
    Detecting the provisioner...
    Error getting SSH command: Something went wrong running an SSH command!
    command : cat /etc/os-release
    err     : exit status 255
    output  :
    Setting environment variables for machine default...


                            ##         .
                      ## ## ##        ==
                   ## ## ## ## ##    ===
               /"""""""""""""""""\___/ ===
          ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
               \______ o           __/
                 \    \         __/
                  \____\_______/


    Error getting IP address: Host is not running
    docker is configured to use the default machine with IP
    For help getting started, check out the docs at https://docs.docker.com

    Error running connection boilerplate: default is not running. Please start it in order to use the connection settings
    csu:~$

**Comment by ciberado** [comment] 2015-11-30 13:30
I solved it by uninstalling Virtualbox , *removing all the Virtualbox network adaptars using the control panel* and reinstalling the last stable version of the Docker toolbox.

**Comment by csu** [comment] 2015-12-01 05:18
I'm still getting the same problem even after doing those steps :( I managed to get it working on another Mac though (one that never had VirtualBox installed on it before). I did previously have VirtualBox installed on the machine that Docker isn't working on.

**Comment by csu** [comment] 2015-12-01 05:52
I'm still having trouble with this. @ciberado What do you mean by "removing all the VirtualBox network adapters using the control panel"? What control panel?

**Comment by mmrko** [comment] 2015-12-04 18:24
I ran into this issue (regardless of which VBox or Docker Machine version I was using) while running things as `sudo`. Not running my setup script as `sudo` helped fix things.

**Comment by csu** [comment] 2015-12-05 03:32
@mmrko which setup script are you referring to?

**Comment by mmrko** [comment] 2015-12-05 03:36
Just a light wrapper around `docker-compose` I wrote that calls `docker-machine --debug create -d virtualbox --virtualbox-memory 2048 dev`.

**Comment by nasserahmed** [comment] 2015-12-09 20:51
OSX: v10.11.2 (El Capitan)
Virtualbox: 5.0.10r104061
Docker version 1.9.1, build a34a1d5

The following worked for me:
https://github.com/docker/machine/issues/1801#issuecomment-147101937

**Comment by udoless** [comment] 2015-12-10 02:42
+1

**Comment by xuqingkuang** [comment] 2015-12-11 10:37
@adyromantika Same issue resolved by your solution, thanks a lot.

**Comment by JamesMilnerUK** [comment] 2015-12-23 01:15
Having this issue on
Windows 10, 
Version 5.0.10 r104061

Docker:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64

**Comment by dp80** [comment] 2016-01-04 21:31
I have same issue as well on windows 8.1, 
Docker: 
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      windows/amd64

virtual box default image log:
```
00:00:01.740052 IntNet#0: szNetwork={HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2} enmTrunkType=3 szTrunk={\DEVICE\{BBC7186C-E7AE-4EB4-949C-38167867C12A}} fFlags=0x8000 cbRecv=325632 cbSend=196608 fIgnoreConnectFailure=false
00:00:01.740112 VMSetError: F:\tinderbox\win-5.0\src\VBox\Devices\Network\DrvIntNet.cpp(1753) int __cdecl drvR3IntNetConstruct(struct PDMDRVINS *,struct CFGMNODE *,unsigned int); rc=VERR_INTNET_FLT_IF_NOT_FOUND
00:00:01.740130 VMSetError: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2'
00:00:01.740170 VMSetError: F:\tinderbox\win-5.0\src\VBox\Devices\Network\DevE1000.cpp(7715) int __cdecl e1kR3Construct(struct PDMDEVINS *,int,struct CFGMNODE *); rc=VERR_INTNET_FLT_IF_NOT_FOUND
00:00:01.740172 VMSetError: Failed to attach the network LUN
00:00:01.740189 PDM: Failed to construct 'e1000'/1! VERR_INTNET_FLT_IF_NOT_FOUND (-3600) - The networking interface to filter was not found.
00:00:01.774440 NAT: zone(nm:mbuf_cluster, used:0)
00:00:01.774877 NAT: zone(nm:mbuf_packet, used:0)
00:00:01.774894 NAT: zone(nm:mbuf, used:0)
00:00:01.774996 NAT: zone(nm:mbuf_jumbo_pagesize, used:0)
00:00:01.775437 NAT: zone(nm:mbuf_jumbo_9k, used:0)
00:00:01.775718 NAT: zone(nm:mbuf_jumbo_16k, used:0)
00:00:01.775846 NAT: zone(nm:mbuf_ext_refcnt, used:0)
00:00:01.776838 GIM: KVM: Resetting MSRs
00:00:01.778203 ERROR [COM]: aRC=E_FAIL (0x80004005) aIID={872da645-4a9b-1727-bee2-5585105b9eed} aComponent={ConsoleWrap} aText={Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
00:00:01.778227 Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)}, preserve=false aResultDetail=0
00:00:01.778520 Console: Machine state changed to 'PoweredOff'
00:00:01.820329 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))
```
The DHCP server is enable on my network interface as suggested to check in earlier posts.

**Comment by xiam** [comment] 2016-01-09 00:51
Also had this problem on OSX, this comment https://github.com/docker/toolbox/issues/273#issuecomment-157805699 helped me.

**Comment by yutaf** [comment] 2016-01-13 03:58
This might be a solution.
<http://qiita.com/shigure_onishi/items/3b66e41150ed8b0a7c96>

```
$ VBoxManage list hostonlyifs | grep -e '^Name'
Name:            vboxnet0
Name:            vboxnet1
Name:            vboxnet2
Name:            vboxnet3
Name:            vboxnet4
Name:            vboxnet5
Name:            vboxnet6
$ VBoxManage hostonlyif remove vboxnet0
$ VBoxManage hostonlyif remove vboxnet1
$ VBoxManage hostonlyif remove vboxnet2
$ VBoxManage hostonlyif remove vboxnet3
$ VBoxManage hostonlyif remove vboxnet4
$ VBoxManage hostonlyif remove vboxnet5
$ VBoxManage hostonlyif remove vboxnet6
```

The author says that this is caused by network problem and that Vagrant's IP and Docker machine's may collide if you have used Vagrant.

**Comment by ricogallo** [comment] 2016-01-13 14:01
This comment helped me too. https://github.com/docker/toolbox/issues/273#issuecomment-157805699
I hope this will find its place in the docs.

**Comment by mariohmol** [comment] 2016-01-25 14:33
Tested all solutions here with no success. My last option will be remove default machine and build it again. My DHCP was already configured and restart didnt work. I'm suing OSC 10.11.
To work i had to change the VM NetWork from Bridge to NAT. I changed it to NAT before to solve this problem : https://github.com/npm/npm/issues/8836

**Comment by f3rdy** [comment] 2016-01-29 07:23
It's really a mess. I'm trying to show the colleagues how easy it is to get docker working on windows but it's constantly messaging: 

`Error creating machine: Error in driver during machine creation: Unable to start the VM: exit status 1`

whenever I start up docker quickstart terminal. The vbox.log says: http://pastebin.com/eqTTvU6D

I tried to completely get rid of virtualbox, virtualbox files, virtual network adapters, docker configuration files and rebootet, re-installed and got this again. Maybe the better solution is to provide a vbox image with a running docker linux myself for demonstration purposes. The whole shiny docker toolbox is not working.

**Comment by JigSawFr** [comment] 2016-02-02 12:59
@f3rdy same problem.... it was working in past days, but now this error is shown.

**Comment by Slaventsiy** [comment] 2016-02-11 16:33
Had the same issue. Running the quickstart with administrator rights fixed the issue.

**Comment by skale1990** [comment] 2016-02-12 18:26
+1

**Comment by skale1990** [comment] 2016-02-12 18:27
after executing, docker quickstart terminal::

Running pre-create checks...
Creating machine...
(default) Copying C:\Users\SOKALE.ORADEV\.docker\machine\cache\boot2docker.iso t
o C:\Users\SOKALE.ORADEV\.docker\machine\machines\default\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Windows might ask for the permission to create a network adapter. Some
times, such confirmation window is minimized in the taskbar.
(default) Found a new host-only adapter: "VirtualBox Host-Only Ethernet Adapter
#2"
(default) Windows might ask for the permission to configure a network adapter. S
ometimes, such confirmation window is minimized in the taskbar.
Error creating machine: Error in driver during machine creation: Unable to start
 the VM: exit status 1
Details: 00:00:01.752878 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E
_FAIL (0X80004005))
Looks like something went wrong... Press any key to continue...

**Comment by magamlag** [comment] 2016-02-14 23:41
+1

**Comment by jeffdm** [comment] 2016-02-25 23:44
Merging with https://github.com/docker/toolbox/issues/153

**Closed by jeffdm** 2016-02-25 23:44 UTC
